from django.urls import path, re_path

from django_ip_safeguard.contrib.admin_frontend.views import (
    serve_frontend_build_file,
    serve_frontend_spa,
    serve_frontend_static_file,
)
from django_ip_safeguard.views import (
    access_log_export_view,
    access_log_list_view,
    access_log_user_summary_view,
    api_key_create_view,
    api_key_list_view,
    api_key_login_view,
    api_key_logs_view,
    api_key_revoke_view,
    auth_me_view,
    ban_ip_view,
    ban_list_view,
    change_email_view,
    change_password_view,
    csrf_view,
    dashboard_api_view,
    django_admin_group_list_view,
    django_admin_user_detail_view,
    django_admin_users_collection_view,
    geo_pools_status_view,
    geo_pools_sync_view,
    health_view,
    i18n_lang_list_view,
    i18n_lang_switch_view,
    jwt_login_view,
    jwt_logout_view,
    jwt_refresh_view,
    login_view,
    logout_view,
    metrics_api_view,
    metrics_reset_view,
    policies_collection_view,
    policy_detail_by_name_view,
    policy_snapshot_rollback_view,
    policy_snapshots_list_view,
    policy_view,
    recent_records_view,
    scheduled_task_detail_view,
    scheduled_task_list_view,
    scheduled_task_run_view,
    security_audit_log_view,
    system_settings_view,
    two_factor_disable_view,
    two_factor_login_verify_view,
    two_factor_setup_view,
    two_factor_status_view,
    two_factor_verify_view,
    unban_ip_view,
    user_profile_view,
    user_stats_chart_view,
    verify_email_view,
)

app_name = "django_ip_safeguard"

urlpatterns = [
    path("api/auth/csrf/", csrf_view, name="auth_csrf_api"),
    path("api/auth/login/", login_view, name="auth_login_api"),
    path("api/auth/jwt/login/", jwt_login_view, name="auth_jwt_login_api"),
    path("api/auth/jwt/refresh/", jwt_refresh_view, name="auth_jwt_refresh_api"),
    path("api/auth/jwt/logout/", jwt_logout_view, name="auth_jwt_logout_api"),
    path("api/auth/logout/", logout_view, name="auth_logout_api"),
    path("api/auth/me/", auth_me_view, name="auth_me_api"),
    path("api/auth/change-password/", change_password_view, name="change_password_api"),
    path("api/auth/change-email/", change_email_view, name="change_email_api"),
    path("api/auth/verify-email/", verify_email_view, name="verify_email_api"),
    path("api/auth/profile/", user_profile_view, name="user_profile_api"),
    path("api/auth/2fa/status/", two_factor_status_view, name="two_factor_status_api"),
    path("api/auth/2fa/setup/", two_factor_setup_view, name="two_factor_setup_api"),
    path("api/auth/2fa/verify/", two_factor_verify_view, name="two_factor_verify_api"),
    path("api/auth/2fa/disable/", two_factor_disable_view, name="two_factor_disable_api"),
    path("api/auth/2fa/login-verify/", two_factor_login_verify_view, name="two_factor_login_verify_api"),
    path("api/auth/api-key/login/", api_key_login_view, name="api_key_login_api"),
    path("api/auth/api-key/list/", api_key_list_view, name="api_key_list_api"),
    path("api/auth/api-key/create/", api_key_create_view, name="api_key_create_api"),
    path("api/auth/api-key/revoke/", api_key_revoke_view, name="api_key_revoke_api"),
    path("api/auth/api-key/logs/", api_key_logs_view, name="api_key_logs_api"),
    path("api/dashboard/", dashboard_api_view, name="dashboard_api"),
    path("api/recent-records/", recent_records_view, name="recent_records_api"),
    path("api/metrics/", metrics_api_view, name="metrics_api"),
    path("api/metrics/reset/", metrics_reset_view, name="metrics_reset_api"),
    path("api/policies/", policies_collection_view, name="policies_collection_api"),
    path("api/policies/<str:pname>/", policy_detail_by_name_view, name="policy_detail_by_name_api"),
    path(
        "api/policy/snapshots/<int:snapshot_id>/rollback/",
        policy_snapshot_rollback_view,
        name="policy_snapshot_rollback_api",
    ),
    path("api/policy/snapshots/", policy_snapshots_list_view, name="policy_snapshots_list_api"),
    path("api/policy/", policy_view, name="policy_api"),
    path("api/geo-pools/status/", geo_pools_status_view, name="geo_pools_status_api"),
    path("api/geo-pools/sync/", geo_pools_sync_view, name="geo_pools_sync_api"),
    path("api/ban/", ban_ip_view, name="ban_ip_api"),
    path("api/unban/", unban_ip_view, name="unban_ip_api"),
    path("api/ban-list/", ban_list_view, name="ban_list_api"),
    path("api/access-logs/", access_log_list_view, name="access_log_list_api"),
    path("api/access-logs/export/", access_log_export_view, name="access_log_export_api"),
    path("api/access-logs/user-summary/", access_log_user_summary_view, name="access_log_user_summary_api"),
    path("api/health/", health_view, name="health_api"),
    path("api/i18n/languages/", i18n_lang_list_view, name="i18n_lang_list_api"),
    path("api/i18n/switch/", i18n_lang_switch_view, name="i18n_lang_switch_api"),
    path("api/user-stats-chart/", user_stats_chart_view, name="user_stats_chart_api"),
    path("api/security-audit-logs/", security_audit_log_view, name="security_audit_log_api"),
    path("api/system-settings/", system_settings_view, name="system_settings_api"),
    path("api/scheduled-tasks/", scheduled_task_list_view, name="scheduled_task_list_api"),
    path("api/scheduled-tasks/<int:task_id>/", scheduled_task_detail_view, name="scheduled_task_detail_api"),
    path("api/scheduled-tasks/<int:task_id>/run/", scheduled_task_run_view, name="scheduled_task_run_api"),
    path("api/admin/groups/", django_admin_group_list_view, name="django_admin_group_list_api"),
    path("api/admin/users/", django_admin_users_collection_view, name="django_admin_users_collection_api"),
    path("api/admin/users/<int:user_id>/", django_admin_user_detail_view, name="django_admin_user_detail_api"),
    # Vue 构建产物与 SPA（须在 api/ 之后，避免吞掉接口路由）
    re_path(r"^assets/(?P<path>.+)$", serve_frontend_build_file, name="admin_frontend_assets"),
    # 根目录静态文件（如 /ip-guard/logo.svg、/ip-guard/favicon.ico）
    re_path(
        r"^(?P<path>(?!api/)(?!assets/).+\.(?:svg|png|jpg|jpeg|gif|ico|webp|txt|map|json|webmanifest|woff|woff2|ttf|eot))$",
        serve_frontend_static_file,
        name="admin_frontend_static",
    ),
    path("", serve_frontend_spa, name="dashboard"),
    re_path(r"^(?!api/)(?!assets/).+$", serve_frontend_spa, name="admin_frontend_spa"),
]
