version: '1.0'
name: pr-pipeline
displayName: PRPipeline
stages:
  - stage: 
    name: compile
    displayName: 编译
    steps:
      - step: build@python
        name: build_python
        displayName: Python 构建
        pythonVersion: '3.10'
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./
        commands:
          - python3 -m pip install --upgrade pip
          - pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
          - pip3 install -r requirements.txt
          - pip3 install -e .
          - python3 ./main.py
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: output
        dependsOn: build_python
triggers:
  pr:
    branches:
      include:
        - master
