# Generated by Django 4.2.27 on 2026-04-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ip_safeguard', '0003_ipguardpolicy_geo_pools_ipgeopoolstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpReputationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True, verbose_name='IP')),
                ('country_code', models.CharField(blank=True, default='', max_length=16, verbose_name='国家码')),
                ('asn', models.IntegerField(blank=True, null=True, verbose_name='ASN编号')),
                ('risk_score', models.IntegerField(default=0, verbose_name='风险分')),
                ('risk_tags', models.JSONField(blank=True, default=list, verbose_name='风险标签')),
                ('is_datacenter', models.BooleanField(default=False, verbose_name='数据中心')),
                ('is_proxy', models.BooleanField(default=False, verbose_name='代理')),
                ('is_vpn', models.BooleanField(default=False, verbose_name='VPN')),
                ('is_tor', models.BooleanField(default=False, verbose_name='Tor')),
                ('block_count_1h', models.PositiveIntegerField(default=0, verbose_name='近1小时拦截次数')),
                ('allow_count_1h', models.PositiveIntegerField(default=0, verbose_name='近1小时放行次数')),
                ('block_count_24h', models.PositiveIntegerField(default=0, verbose_name='近24小时拦截次数')),
                ('allow_count_24h', models.PositiveIntegerField(default=0, verbose_name='近24小时放行次数')),
                ('trend', models.CharField(default='stable', help_text='stable=稳定, rising=上升, declining=下降', max_length=16, verbose_name='趋势')),
                ('source', models.CharField(default='auto', max_length=32, verbose_name='数据来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'IP信誉历史',
                'verbose_name_plural': 'IP信誉历史',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreatIntelFeedStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_name', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='情报源名称')),
                ('feed_url', models.URLField(blank=True, max_length=512, verbose_name='情报源URL')),
                ('feed_format', models.CharField(default='ip_list', max_length=16, verbose_name='数据格式')),
                ('threat_type', models.CharField(default='unknown', max_length=32, verbose_name='威胁类型')),
                ('auto_ban', models.BooleanField(default=False, verbose_name='自动封禁')),
                ('entry_count', models.PositiveIntegerField(default=0, verbose_name='条目数')),
                ('auto_ban_count', models.PositiveIntegerField(default=0, verbose_name='自动封禁数')),
                ('last_ok_at', models.DateTimeField(blank=True, null=True, verbose_name='上次成功同步时间')),
                ('last_error', models.TextField(blank=True, verbose_name='上次错误信息')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '威胁情报源状态',
                'verbose_name_plural': '威胁情报源状态',
            },
        ),
        migrations.AddField(
            model_name='ipaccesslog',
            name='asn',
            field=models.IntegerField(blank=True, null=True, verbose_name='ASN编号'),
        ),
        migrations.AddField(
            model_name='ipaccesslog',
            name='asn_org',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='ASN组织'),
        ),
        migrations.AddField(
            model_name='ipaccesslog',
            name='city',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='ipaccesslog',
            name='country_name',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='国家名'),
        ),
        migrations.AddField(
            model_name='ipaccesslog',
            name='is_datacenter',
            field=models.BooleanField(default=False, verbose_name='数据中心IP'),
        ),
        migrations.AddField(
            model_name='ipaccesslog',
            name='is_proxy',
            field=models.BooleanField(default=False, verbose_name='代理IP'),
        ),
        migrations.AddField(
            model_name='ipaccesslog',
            name='is_tor',
            field=models.BooleanField(default=False, verbose_name='Tor出口'),
        ),
        migrations.AddField(
            model_name='ipaccesslog',
            name='is_vpn',
            field=models.BooleanField(default=False, verbose_name='VPN IP'),
        ),
        migrations.AddField(
            model_name='ipaccesslog',
            name='region',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='省份/地区'),
        ),
        migrations.AddIndex(
            model_name='ipaccesslog',
            index=models.Index(fields=['ip', '-created_at'], name='idx_ip_created'),
        ),
        migrations.AddIndex(
            model_name='ipaccesslog',
            index=models.Index(fields=['country_code'], name='idx_country'),
        ),
        migrations.AddIndex(
            model_name='ipaccesslog',
            index=models.Index(fields=['asn'], name='idx_asn'),
        ),
        migrations.AddIndex(
            model_name='ipaccesslog',
            index=models.Index(fields=['is_datacenter'], name='idx_datacenter'),
        ),
        migrations.AddIndex(
            model_name='ipaccesslog',
            index=models.Index(fields=['decision', '-created_at'], name='idx_decision_created'),
        ),
        migrations.AddIndex(
            model_name='ipreputationhistory',
            index=models.Index(fields=['ip', '-created_at'], name='idx_reputation_ip_created'),
        ),
        migrations.AddIndex(
            model_name='ipreputationhistory',
            index=models.Index(fields=['risk_score'], name='idx_reputation_risk'),
        ),
        migrations.AddIndex(
            model_name='ipreputationhistory',
            index=models.Index(fields=['trend'], name='idx_reputation_trend'),
        ),
    ]
