# Generated by Django 4.2.27 on 2026-04-25 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_ip_safeguard', '0004_ipreputationhistory_threatintelfeedstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_factor_secret', models.CharField(blank=True, default='', max_length=64, verbose_name='2FA密钥')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='2FA已启用')),
                ('language', models.CharField(blank=True, default='zh-hans', max_length=10, verbose_name='界面语言')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ip_safeguard_profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户安全配置',
                'verbose_name_plural': '用户安全配置',
            },
        ),
    ]
