# Generated by Django 4.2.27 on 2026-04-25 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_ip_safeguard', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_token_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='验证令牌过期时间'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verification_token',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='邮箱验证令牌'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='密码修改时间'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pending_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='待验证邮箱'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='recovery_codes',
            field=models.JSONField(blank=True, default=list, verbose_name='2FA恢复码'),
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=64, verbose_name='密钥名称')),
                ('prefix', models.CharField(db_index=True, max_length=8, verbose_name='密钥前缀')),
                ('key_hash', models.CharField(max_length=128, unique=True, verbose_name='密钥哈希')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'API密钥',
                'verbose_name_plural': 'API密钥',
                'ordering': ['-created_at'],
            },
        ),
    ]
