# Generated by Django 4.2.27 on 2026-04-26 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_ip_safeguard', '0006_userprofile_email_token_expires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='allowed_ips',
            field=models.JSONField(blank=True, default=list, verbose_name='允许的IP列表'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='created_by_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='创建时IP'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='last_used_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='最后使用IP'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='login_failures',
            field=models.IntegerField(default=0, verbose_name='连续登录失败次数'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='max_usage',
            field=models.IntegerField(default=0, verbose_name='最大使用次数'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='usage_count',
            field=models.IntegerField(default=0, verbose_name='已使用次数'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_fail_count',
            field=models.PositiveIntegerField(default=0, verbose_name='2FA验证失败次数'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_locked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='2FA锁定截止时间'),
        ),
        migrations.CreateModel(
            name='ApiKeyUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('action', models.CharField(default='login', max_length=32, verbose_name='操作')),
                ('success', models.BooleanField(default=True, verbose_name='是否成功')),
                ('failure_reason', models.CharField(blank=True, default='', max_length=128, verbose_name='失败原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='django_ip_safeguard.apikey', verbose_name='API密钥')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_key_usage_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'API密钥使用日志',
                'verbose_name_plural': 'API密钥使用日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='django_ip_s_created_f7fdbe_idx'), models.Index(fields=['api_key', '-created_at'], name='django_ip_s_api_key_d024df_idx')],
            },
        ),
    ]
