# Generated by Django 6.0.4 on 2026-04-26 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ip_safeguard', '0008_add_apikey_usage_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='任务名称')),
                ('task_type', models.CharField(choices=[('geoip2_update', 'GeoIP2 数据库更新'), ('threat_intel_sync', '威胁情报同步'), ('ip_reputation_snapshot', 'IP 信誉快照'), ('geo_pool_sync', '地理IP池同步'), ('custom', '自定义命令')], default='custom', max_length=32, verbose_name='任务类型')),
                ('command', models.CharField(blank=True, help_text='自定义管理命令，如 update_geoip2_db --force', max_length=255, verbose_name='自定义命令')),
                ('cron_expression', models.CharField(blank=True, help_text='自定义 Cron 表达式，如 0 3 * * 1（每周一凌晨3点）', max_length=64, verbose_name='Cron 表达式')),
                ('cron_preset', models.CharField(choices=[('@hourly', '每小时'), ('@daily', '每天'), ('@weekly', '每周'), ('@monthly', '每月'), ('custom', '自定义')], default='@daily', max_length=16, verbose_name='Cron 预设')),
                ('interval_minutes', models.PositiveIntegerField(default=0, help_text='0 表示使用 Cron 预设或自定义表达式', verbose_name='执行间隔(分钟)')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('description', models.TextField(blank=True, default='', verbose_name='任务描述')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='上次执行时间')),
                ('last_run_status', models.CharField(blank=True, default='', max_length=16, verbose_name='上次执行状态')),
                ('last_run_output', models.TextField(blank=True, default='', verbose_name='上次执行输出')),
                ('next_run_at', models.DateTimeField(blank=True, null=True, verbose_name='下次执行时间')),
                ('run_count', models.PositiveIntegerField(default=0, verbose_name='累计执行次数')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='成功次数')),
                ('failure_count', models.PositiveIntegerField(default=0, verbose_name='失败次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scheduled_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '定时任务',
                'verbose_name_plural': '定时任务',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaskExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=16, verbose_name='执行状态')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='执行耗时(毫秒)')),
                ('output', models.TextField(blank=True, default='', verbose_name='执行输出')),
                ('error', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='django_ip_safeguard.scheduledtask', verbose_name='定时任务')),
            ],
            options={
                'verbose_name': '任务执行日志',
                'verbose_name_plural': '任务执行日志',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='taskexecutionlog',
            index=models.Index(fields=['task', '-started_at'], name='django_ip_s_task_id_032f0c_idx'),
        ),
    ]
